### ISSUE TITLE
Build of pytroll_base_image fails: ImportError

### ISSUE THREAD

**Issue by ThomasDahlDMI** [nordsat/shared-docker-files#6]
I am currently trying to follow the instructions for the pytroll_base_image. But the command
`docker build -t pytroll_base_image -f build_dir/Dockerfile_ubuntu build_dir`
is failing as such:
```
...

Looking for: ['conda']


Pinned packages:
  - python 3.9.*


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mamba/mamba.py", line 914, in main
    from conda.common.compat import ensure_text_type, init_std_stream_encoding
ImportError: cannot import name 'init_std_stream_encoding' from 'conda.common.compat' (/opt/conda/lib/python3.9/site-packages/conda/common/compat.py)
The command '/bin/sh -c curl -L -o Mambaforge-latest-Linux-x86_64.sh https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh &&     sh Mambaforge-latest-Linux-x86_64.sh -b -p /opt/conda &&     rm Mambaforge-latest-Linux-x86_64.sh &&     echo ". /opt/conda/etc/profile.d/conda.sh" >> /root/.bashrc &&     echo "conda activate base" >> /root/.bashrc &&     . /root/.bashrc &&     mamba update -n base conda &&     mamba update --all &&     mamba clean -a -y' returned a non-zero code: 1

```

I have tried changing the version of Mambaforge from the latest version (4.12.0-2) to 4.12.0 but have had no luck.
Can you help me pinpoint what's going wrong?

**Comment by pnuu** [comment]
Ok, got Docker settings in place to get this far. I also see the same error, but don't know what's happening. I'll be investigating this a bit today and maybe tommorrow, then I'll be on holiday until August.

**Comment by pnuu** [comment]
I ran the commands from `Dockerfile_ubuntu` one by one outside of Docker and get the same error from `mamba update --all`. If I instead do `conda update --all` things work as expected.

**Comment by pnuu** [comment]
Ooh, now I remember. Upgrading `conda` to version 4.13.0 breaks `mamba`, see https://github.com/mamba-org/mamba/issues/1724

For now, I think the easiest way to work around this is to remove the `mamba update -n base conda && \` command from the Dockerfile (or just add `#` at the start of the line).

**Comment by pnuu** [comment]
Another workaround is to change that line to `mamba update -y -n base 'conda!=4.13.0' && \` so that that particular Conda version will not be installed.
